import '../enums/filter_type.dart';
import '../models/image_item_model.dart';

final List<ImageItem> staggeredImagePoolMock = [
  const ImageItem(
    url: 'assets/images/doggie.png',
    width: 200.0,
    height: 150.0,
    types: [FilterType.classicos, FilterType.stickers, FilterType.prints],
    title: 'Doggie Collection',
    description: 'Uma coleção incrível do nosso mais antigo personagem',
    variations: ['assets/images/doggie.png', 'assets/images/doggieRosa.png'],
    hasARFilter: true,
    marketable: true,
    size: '9x6',
    weight: '3g',
    price: 4.50,
  ),
  const ImageItem(
    url: 'assets/images/gato.jpg',
    width: 180.0,
    height: 220.0,
    types: [FilterType.collabs, FilterType.novos],
    title: 'Gato Collab',
    description: 'Colaboração especial com artistas locais',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/caxinCollab.png',
    width: 160.0,
    height: 200.0,
    types: [FilterType.collabs, FilterType.stickers],
    title: 'Caxin Collab',
    description: 'Projeto colaborativo exclusivo',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/pimp.png',
    width: 220.0,
    height: 180.0,
    types: [FilterType.classicos, FilterType.prints],
    title: 'Pimp Classic',
    description: 'Design clássico atemporal',
    variations: ['assets/images/pimp.png'],
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/festival.jpg',
    width: 200.0,
    height: 160.0,
    types: [FilterType.prints, FilterType.collabs],
    title: 'Festival Print',
    description: 'Arte para impressão em alta qualidade',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/fakepng.png',
    width: 180.0,
    height: 240.0,
    types: [FilterType.stickers, FilterType.novos],
    title: 'Fake Sticker',
    description: 'Adesivo exclusivo da coleção',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/noidRuaDoggie.jpg',
    width: 190.0,
    height: 170.0,
    types: [FilterType.novos, FilterType.classicos],
    title: 'No ID Rua Doggie',
    description: 'Novo design da série Rua',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/doggie.png',
    width: 210.0,
    height: 190.0,
    types: [FilterType.prints, FilterType.stickers],
    title: 'Doggie Print',
    description: 'Versão para impressão do Doggie',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/gato.jpg',
    width: 170.0,
    height: 210.0,
    types: [FilterType.classicos, FilterType.prints],
    title: 'Gato Classic',
    description: 'Versão clássica do Gato',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/caxinCollab.png',
    width: 200.0,
    height: 180.0,
    types: [FilterType.stickers, FilterType.collabs],
    title: 'Caxin Sticker',
    description: 'Adesivo da colaboração Caxin',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/pimp.png',
    width: 180.0,
    height: 200.0,
    types: [FilterType.novos, FilterType.collabs],
    title: 'Pimp New',
    description: 'Nova versão do Pimp',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/festival.jpg',
    width: 190.0,
    height: 170.0,
    types: [FilterType.stickers, FilterType.novos],
    title: 'Festival Sticker',
    description: 'Adesivo do Festival',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/fakepng.png',
    width: 200.0,
    height: 160.0,
    types: [FilterType.prints, FilterType.classicos],
    title: 'Fake Print',
    description: 'Versão para impressão do Fake',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/noidRuaDoggie.jpg',
    width: 180.0,
    height: 220.0,
    types: [FilterType.collabs, FilterType.stickers],
    title: 'No ID Collab',
    description: 'Colaboração No ID',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/doggie.png',
    width: 160.0,
    height: 200.0,
    types: [FilterType.novos, FilterType.prints],
    title: 'Doggie New',
    description: 'Nova versão do Doggie',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/gato.jpg',
    width: 210.0,
    height: 180.0,
    types: [FilterType.stickers, FilterType.collabs],
    title: 'Gato Sticker',
    description: 'Adesivo do Gato',
    isCollab: true,
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/caxinCollab.png',
    width: 170.0,
    height: 210.0,
    types: [FilterType.prints, FilterType.novos],
    title: 'Caxin Print',
    description: 'Versão para impressão do Caxin',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/pimp.png',
    width: 200.0,
    height: 160.0,
    types: [FilterType.stickers, FilterType.classicos],
    title: 'Pimp Sticker',
    description: 'Adesivo do Pimp',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/festival.jpg',
    width: 180.0,
    height: 240.0,
    types: [FilterType.novos, FilterType.prints],
    title: 'Festival New',
    description: 'Nova versão do Festival',
    price: 20.0,
  ),
  const ImageItem(
    url: 'assets/images/fakepng.png',
    width: 190.0,
    height: 170.0,
    types: [FilterType.collabs, FilterType.stickers],
    title: 'Fake Collab',
    description: 'Colaboração Fake',
    isCollab: true,
    price: 20.0,
  ),
];
